// automatically generated by the FlatBuffers compiler, do not modify

import { Json } from './json.js';
import { Topical } from './topical.js';


export enum MessageType {
  NONE = 0,
  Json = 1,
  Topical = 2
}

export function unionToMessageType(
  type: MessageType,
  accessor: (obj:Json|Topical) => Json|Topical|null
): Json|Topical|null {
  switch(MessageType[type]) {
    case 'NONE': return null; 
    case 'Json': return accessor(new Json())! as Json;
    case 'Topical': return accessor(new Topical())! as Topical;
    default: return null;
  }
}

export function unionListToMessageType(
  type: MessageType, 
  accessor: (index: number, obj:Json|Topical) => Json|Topical|null, 
  index: number
): Json|Topical|null {
  switch(MessageType[type]) {
    case 'NONE': return null; 
    case 'Json': return accessor(index, new Json())! as Json;
    case 'Topical': return accessor(index, new Topical())! as Topical;
    default: return null;
  }
}
