// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class TopicPost {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TopicPost {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTopicPost(bb:flatbuffers.ByteBuffer, obj?:TopicPost):TopicPost {
  return (obj || new TopicPost()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTopicPost(bb:flatbuffers.ByteBuffer, obj?:TopicPost):TopicPost {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TopicPost()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

body():string|null
body(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
body(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startTopicPost(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addBody(builder:flatbuffers.Builder, bodyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, bodyOffset, 0);
}

static endTopicPost(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createTopicPost(builder:flatbuffers.Builder, bodyOffset:flatbuffers.Offset):flatbuffers.Offset {
  TopicPost.startTopicPost(builder);
  TopicPost.addBody(builder, bodyOffset);
  return TopicPost.endTopicPost(builder);
}
}
